### ISSUE TITLE
Include thrift idl files in repo

### ISSUE THREAD

**Issue by flandr** [Evernote/evernote-sdk-cpp#2]
Instead of only including the generated C++ bindings, could you please include the Thrift IDL files in the repository? This is both a more concise reference to program to and also allows developers to generate bindings w/ custom parameters (e.g. the Cob-style c++ RPC clients).

**Comment by atejeda** [comment]
+1

**Comment by d1vanov** [comment]
Isn't this what you are looking for? https://github.com/evernote/evernote-thrift

**Comment by flandr** [comment]
Absolutely; somehow overlooked that. Thanks!
